name: Continuous integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
